export const meetingKnowledgeRequiredRelations = [
  "meeting_core.answer_effects",
  "meeting_core.conversation_one_shot_receipts",
  "meeting_knowledge.question_jobs",
  "meeting_knowledge.question_rate_reservations",
  "meeting_knowledge.unavailable_final_projections",
  "meeting_knowledge.live_memory_meetings",
  "meeting_knowledge.live_memory_outbox",
  "meeting_knowledge.live_memory_hot_tail",
] as const;

export const meetingKnowledgeRequiredIndexes = [
  "meeting_core.answer_effects_unknown_idx",
  "meeting_knowledge.question_jobs_dedupe_idx",
  "meeting_knowledge.question_jobs_leasable_idx",
  "meeting_knowledge.question_rate_requester_window_idx",
  "meeting_knowledge.question_rate_scope_window_idx",
  "meeting_knowledge.live_memory_outbox_recoverable_idx",
  "meeting_knowledge.live_memory_hot_tail_generation_idx",
] as const;

export const meetingKnowledgeRequiredColumns = [
  "meeting_core.answer_effects.effect_id",
  "meeting_core.answer_effects.state",
  "meeting_core.answer_effects.projection_target_container_id",
  "meeting_core.answer_effects.delivery_container_id",
  "meeting_core.answer_effects.reply_to_remote_message_id",
  "meeting_core.answer_effects.marker",
  "meeting_core.answer_effects.payload_bytes",
  "meeting_core.answer_effects.payload_hash",
  "meeting_core.answer_effects.binding_hash",
  "meeting_core.answer_effects.authorization_digest",
  "meeting_core.answer_effects.claim_generation",
  "meeting_core.answer_effects.claim_owner",
  "meeting_core.answer_effects.claim_until",
  "meeting_core.answer_effects.request_started_at",
  "meeting_core.answer_effects.external_receipt",
  "meeting_core.answer_effects.reserved_at",
  "meeting_core.answer_effects.updated_at",
  "meeting_core.answer_effects.settled_at",
  "meeting_core.conversation_one_shot_receipts.receipt_id",
  "meeting_core.conversation_one_shot_receipts.cue_kind",
  "meeting_core.conversation_one_shot_receipts.state",
  "meeting_core.conversation_one_shot_receipts.lease_token",
  "meeting_core.conversation_one_shot_receipts.lease_expires_at",
  "meeting_core.conversation_one_shot_receipts.created_at",
  "meeting_core.conversation_one_shot_receipts.completed_at",
  "meeting_knowledge.question_jobs.question_id",
  "meeting_knowledge.question_jobs.requester_subject",
  "meeting_knowledge.question_jobs.question_hash",
  "meeting_knowledge.question_jobs.scope_id",
  "meeting_knowledge.question_jobs.final_projection_receipt",
  "meeting_knowledge.question_jobs.authorization_principal_ref",
  "meeting_knowledge.question_jobs.authorization_digest",
  "meeting_knowledge.question_jobs.locale",
  "meeting_knowledge.question_jobs.question_text",
  "meeting_knowledge.question_jobs.binding",
  "meeting_knowledge.question_jobs.binding_hash",
  "meeting_knowledge.question_jobs.state",
  "meeting_knowledge.question_jobs.outcome",
  "meeting_knowledge.question_jobs.attempts",
  "meeting_knowledge.question_jobs.generation",
  "meeting_knowledge.question_jobs.lease_owner",
  "meeting_knowledge.question_jobs.lease_until",
  "meeting_knowledge.question_jobs.grounding_plan",
  "meeting_knowledge.question_jobs.grounding_measurement",
  "meeting_knowledge.question_jobs.runtime_profile",
  "meeting_knowledge.question_jobs.answer_candidate",
  "meeting_knowledge.question_jobs.retry_reason",
  "meeting_knowledge.question_jobs.created_at",
  "meeting_knowledge.question_jobs.updated_at",
  "meeting_knowledge.question_jobs.expires_at",
  "meeting_knowledge.question_jobs.ready_at",
  "meeting_knowledge.question_jobs.terminal_at",
  "meeting_knowledge.question_jobs.scrubbed_at",
  "meeting_knowledge.question_rate_reservations.question_id",
  "meeting_knowledge.question_rate_reservations.requester_subject",
  "meeting_knowledge.question_rate_reservations.scope_id",
  "meeting_knowledge.question_rate_reservations.reserved_at",
  "meeting_knowledge.unavailable_final_projections.final_projection_receipt",
  "meeting_knowledge.unavailable_final_projections.unavailable_at",
  "meeting_knowledge.live_memory_meetings.meeting_id",
  "meeting_knowledge.live_memory_meetings.schema_version",
  "meeting_knowledge.live_memory_meetings.scope_id",
  "meeting_knowledge.live_memory_meetings.room_id",
  "meeting_knowledge.live_memory_meetings.producer_capability_id",
  "meeting_knowledge.live_memory_meetings.actor_semantics_version",
  "meeting_knowledge.live_memory_meetings.producer_revision",
  "meeting_knowledge.live_memory_meetings.human_actor_ids",
  "meeting_knowledge.live_memory_meetings.roster_state",
  "meeting_knowledge.live_memory_meetings.identity_generation",
  "meeting_knowledge.live_memory_meetings.source_generation",
  "meeting_knowledge.live_memory_meetings.applied_generation",
  "meeting_knowledge.live_memory_meetings.state",
  "meeting_knowledge.live_memory_outbox.mutation_id",
  "meeting_knowledge.live_memory_outbox.meeting_id",
  "meeting_knowledge.live_memory_outbox.turn_id",
  "meeting_knowledge.live_memory_outbox.source_generation",
  "meeting_knowledge.live_memory_outbox.identity_generation",
  "meeting_knowledge.live_memory_outbox.turn_hash",
  "meeting_knowledge.live_memory_outbox.state",
  "meeting_knowledge.live_memory_outbox.attempt_count",
  "meeting_knowledge.live_memory_outbox.lease_fence",
  "meeting_knowledge.live_memory_outbox.lease_expires_at",
  "meeting_knowledge.live_memory_outbox.retry_after",
  "meeting_knowledge.live_memory_outbox.last_error_code",
  "meeting_knowledge.live_memory_hot_tail.meeting_id",
  "meeting_knowledge.live_memory_hot_tail.turn_id",
  "meeting_knowledge.live_memory_hot_tail.source_generation",
  "meeting_knowledge.live_memory_hot_tail.identity_generation",
  "meeting_knowledge.live_memory_hot_tail.turn_hash",
] as const;

export const meetingKnowledgeRequiredCheckConstraints = [
  ["meeting_core", "answer_effects", "answer_effects_state_is_supported"],
  ["meeting_core", "answer_effects", "answer_effects_payload_hash_is_sha256"],
  ["meeting_core", "answer_effects", "answer_effects_binding_hash_is_sha256"],
  ["meeting_core", "answer_effects", "answer_effects_authorization_digest_is_sha256"],
  ["meeting_core", "answer_effects", "answer_effects_claim_generation_is_valid"],
  ["meeting_core", "answer_effects", "answer_effects_request_receipt_is_consistent"],
  ["meeting_core", "answer_effects", "answer_effects_delivery_receipt_is_consistent"],
  ["meeting_core", "answer_effects", "answer_effects_payload_is_bounded"],
  ["meeting_core", "answer_effects", "answer_effects_terminal_payload_is_scrubbed"],
  ["meeting_core", "answer_effects", "answer_effects_actionable_delivery_is_known"],
  [
    "meeting_core",
    "conversation_one_shot_receipts",
    "conversation_one_shot_receipts_identity_is_valid",
  ],
  [
    "meeting_core",
    "conversation_one_shot_receipts",
    "conversation_one_shot_receipts_state_is_valid",
  ],
  ["meeting_knowledge", "question_jobs", "question_jobs_requester_subject_is_sha256"],
  ["meeting_knowledge", "question_jobs", "question_jobs_question_hash_is_sha256"],
  ["meeting_knowledge", "question_jobs", "question_jobs_authorization_digest_is_sha256"],
  ["meeting_knowledge", "question_jobs", "question_jobs_binding_hash_is_sha256"],
  ["meeting_knowledge", "question_jobs", "question_jobs_locale_is_supported"],
  ["meeting_knowledge", "question_jobs", "question_jobs_state_is_supported"],
  ["meeting_knowledge", "question_jobs", "question_jobs_outcome_is_supported"],
  ["meeting_knowledge", "question_jobs", "question_jobs_attempts_are_bounded"],
  ["meeting_knowledge", "question_jobs", "question_jobs_generation_is_valid"],
  ["meeting_knowledge", "question_jobs", "question_jobs_active_content_is_consistent"],
  ["meeting_knowledge", "question_jobs", "question_jobs_terminal_is_scrubbed"],
  ["meeting_knowledge", "question_jobs", "question_jobs_nonterminal_has_no_outcome"],
  ["meeting_knowledge", "question_jobs", "question_jobs_ready_has_candidate"],
  ["meeting_knowledge", "question_jobs", "question_jobs_expiry_follows_creation"],
  [
    "meeting_knowledge",
    "question_rate_reservations",
    "question_rate_requester_subject_is_sha256",
  ],
  ["meeting_knowledge", "live_memory_meetings", "live_memory_meetings_schema_is_supported"],
  ["meeting_knowledge", "live_memory_meetings", "live_memory_meetings_identity_is_valid"],
  ["meeting_knowledge", "live_memory_meetings", "live_memory_meetings_state_is_supported"],
  ["meeting_knowledge", "live_memory_outbox", "live_memory_outbox_identity_is_valid"],
  ["meeting_knowledge", "live_memory_outbox", "live_memory_outbox_state_is_supported"],
  ["meeting_knowledge", "live_memory_outbox", "live_memory_outbox_lease_is_consistent"],
  ["meeting_knowledge", "live_memory_hot_tail", "live_memory_hot_tail_identity_is_valid"],
] as const;

export const meetingKnowledgeRequiredStructuralConstraints = [
  ["meeting_core", "answer_effects", "answer_effects_pkey", "p"],
  [
    "meeting_core",
    "conversation_one_shot_receipts",
    "conversation_one_shot_receipts_pkey",
    "p",
  ],
  ["meeting_knowledge", "question_jobs", "question_jobs_pkey", "p"],
  [
    "meeting_knowledge",
    "question_rate_reservations",
    "question_rate_reservations_pkey",
    "p",
  ],
  [
    "meeting_knowledge",
    "question_rate_reservations",
    "question_rate_reservations_question_id_fkey",
    "f",
  ],
  [
    "meeting_knowledge",
    "unavailable_final_projections",
    "unavailable_final_projections_pkey",
    "p",
  ],
  ["meeting_knowledge", "live_memory_meetings", "live_memory_meetings_pkey", "p"],
  [
    "meeting_knowledge",
    "live_memory_meetings",
    "live_memory_meetings_meeting_id_fkey",
    "f",
  ],
  ["meeting_knowledge", "live_memory_outbox", "live_memory_outbox_pkey", "p"],
  [
    "meeting_knowledge",
    "live_memory_outbox",
    "live_memory_outbox_meeting_id_fkey",
    "f",
  ],
  [
    "meeting_knowledge",
    "live_memory_outbox",
    "live_memory_outbox_meeting_id_turn_id_fkey",
    "f",
  ],
  [
    "meeting_knowledge",
    "live_memory_outbox",
    "live_memory_outbox_meeting_generation_unique",
    "u",
  ],
  [
    "meeting_knowledge",
    "live_memory_outbox",
    "live_memory_outbox_meeting_turn_unique",
    "u",
  ],
  ["meeting_knowledge", "live_memory_hot_tail", "live_memory_hot_tail_pkey", "p"],
  [
    "meeting_knowledge",
    "live_memory_hot_tail",
    "live_memory_hot_tail_meeting_id_fkey",
    "f",
  ],
  [
    "meeting_knowledge",
    "live_memory_hot_tail",
    "live_memory_hot_tail_meeting_id_turn_id_fkey",
    "f",
  ],
  [
    "meeting_knowledge",
    "live_memory_hot_tail",
    "live_memory_hot_tail_meeting_generation_unique",
    "u",
  ],
] as const;
