/**
 * Generated by scripts/generate-hosted-campaign-compiled-release.ts.
 * The repository default is deliberately unadmitted and production remains
 * fail closed until a reviewed release build replaces this exact source.
 */
export const GENERATED_HOSTED_CAMPAIGN_COMPILED_RELEASE = Object.freeze({
  generatorVersion: 3,
  schemaVersion: 3,
  status: "unadmitted",
} as const);
