export const meetingVocabulary = [
  "BullMQ",
  "Craig",
  "Craig recording",
  "Dima",
  "Discord",
  "Discord thread",
  "idempotency key",
  "Iliya",
  "landing page",
  "landing slug",
  "live Pipecat assistant",
  "Marina",
  "Mark",
  "Meeting Platform",
  "Nazar",
  "Pipecat",
  "PostgreSQL",
  "PostgreSQL pipeline",
  "QID",
  "Quanta",
  "Quanta ID",
  "Quanta Pages",
  "Redis",
  "Redis queue",
  "referral code",
  "referral link",
  "timestamp",
  "Vlad",
] as const;

// Batch and summary retain their original request content and identity.
export const liveMeetingVocabulary = meetingVocabulary.map((term) =>
  term === "live Pipecat assistant" ? "Pipecat assistant" : term,
);
