export const meetingVocabulary = [
  "BullMQ",
  "Craig",
  "Craig recording",
  "Discord",
  "Discord thread",
  "idempotency key",
  "landing page",
  "landing slug",
  "live Pipecat assistant",
  "Meeting Platform",
  "Pipecat",
  "PostgreSQL",
  "PostgreSQL pipeline",
  "QID",
  "Quanta",
  "Quanta ID",
  "Quanta Pages",
  "Redis",
  "Redis queue",
  "referral code",
  "referral link",
  "timestamp",
] as const;
